/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#ifndef __RAML2AGL_CLASS_SENSORINTERFACE_H_
#define __RAML2AGL_CLASS_SENSORINTERFACE_H_

#pragma once
#include <cstddef>
#include <string.h>
#include <string>
#include <WebSocketApi.h>

extern "C"
{
    #define AFB_BINDING_VERSION 2
    #include <afb/afb-binding.h>
};

class SensorInterface : public WebSocketApi {
public:

  SensorInterface();
  
    /** Autogenrated doc for getdata */
    int getdata(double &out_sensor_data,
        int &out_sensor_id);

    /** Autogenrated doc for setupsensor */
    int setupsensor(const int in_param1,
        const char * in_param2);

};

#endif //__RAML2AGL_CLASS_SENSORINTERFACE_H_