/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#include <service/ServiceSetGetter.h>


/** Autogenrated doc for get */
int ServiceSetGetter::get(int &out_default) {

  AFB_NOTICE("[ServiceSetGetter] Get");
  AFB_ERROR("Method Get not implemented");

  return -1;
}

/** Autogenrated doc for set */
int ServiceSetGetter::set(const int in_default) {

  AFB_NOTICE("[ServiceSetGetter] Set");
  AFB_ERROR("Method Set not implemented");

  return -1;
}
