/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
extern "C"
{
   #define AFB_BINDING_VERSION 2
   #include <afb/afb-binding.h>
};


#include <cstddef>
#include <cstdio>
#include <cstring>

#include <json-c/json.h>

#include <service/ServiceSetGetter.h>
// #include <all_types.h>

static ServiceSetGetter obj;

static int init()
{
	AFB_NOTICE("Initializing... ");
  // Do something
	AFB_NOTICE("Initialization done!");
	return 0;
}

static void set(struct afb_req request) {
  json_object *args = afb_req_json(request);
  json_object *val = NULL;
  int ret = 0;

  AFB_NOTICE("[setgetter] Calling set");

  if (args) {
      if (!json_object_object_get_ex(args, "default", &val)) {
        AFB_ERROR("[setgetter] No 'default' param provided");
        afb_req_fail(request, "bad-request", "No 'default' param provided");
        return;
      }
  }

  ret = obj.set(json_object_object_get_ex(args, "default", &val) ? json_object_get_int(val) : static_cast<int>(0));
  if (ret) {
    AFB_ERROR("[setgetter] Verb 'set' returning error");
    afb_req_fail_f(request, "bad-request", "Verb 'set' returning error %d", ret);
    return;
  }


  afb_req_success(request, args, NULL);

}

static void get(struct afb_req request) {
  json_object *args = afb_req_json(request);
  int _var_default = static_cast<int>(0);
  json_object * new_json = json_object_new_object();
  json_object * new_sub_json = NULL;
  int ret = 0;

  AFB_NOTICE("[setgetter] Calling get");

  ret = obj.get(_var_default);
  if (ret) {
    AFB_ERROR("[setgetter] Verb 'get' returning error");
    afb_req_fail_f(request, "bad-request", "Verb 'get' returning error %d", ret);
    return;
  }

  new_sub_json = json_object_new_int(_var_default);
  json_object_object_add(new_json, "default", new_sub_json);

  afb_req_success(request, new_json, NULL);
  json_object_put(new_json);

}


// static const struct afb_auth _afb_auths_v2_monitor[] = {
// 	{type : afb_auth_Permission, text : "urn:AGL:permission:monitor:public:set"},
// 	{type : afb_auth_Permission, text : "urn:AGL:permission:monitor:public:get"},
// 	{type : afb_auth_Or, first : &_afb_auths_v2_monitor[1], next : &_afb_auths_v2_monitor[0]}
// };

static const struct afb_verb_v2 verbs[] = {
	/*Without security*/
	{.verb = "set", .callback = set, .auth = NULL, .info = "Setup", .session = 0},
	{.verb = "get", .callback = get, .auth = NULL, .info = "Get Data", .session = 0},
	{.verb= NULL, .callback=NULL, .auth = NULL, .info = NULL, .session = 0 }
};

const struct afb_binding_v2 afbBindingV2 = {
	.api = "setgetter",
	.specification = "",
  .info = "Auto generated - Set Getter",
	.verbs = verbs,
	.preinit = NULL,
	.init = init,
	.onevent = NULL,
	.noconcurrency = 1
};