/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#include <service/ServiceSensorInterface.h>


/** Autogenrated doc for getdata */
int ServiceSensorInterface::getdata(double &out_sensor_data,
    int &out_sensor_id) {

  AFB_NOTICE("[ServiceSensorInterface] Getdata");
  AFB_ERROR("Method Getdata not implemented");

  return -1;
}

/** Autogenrated doc for setupsensor */
int ServiceSensorInterface::setupsensor(const int in_param1,
    const char * in_param2) {

  AFB_NOTICE("[ServiceSensorInterface] Setupsensor");
  AFB_ERROR("Method Setupsensor not implemented");

  return -1;
}
